sudo: required

env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost

rvm:
  - 2.3.1

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database cubiware_test;' -U postgres
  - cp -v config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:schema:load

script:
  - bundle exec rspec

services:
  - postgresql

addons:
  code_climate:
    repo_token: 73b2b503c9d6147acc8c12e8a6d1326212500f39bc7500547e6b16af7dde13ad
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
