connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *connection
  database: cubiware_development

test:
  <<: *connection
  database: cubiware_test

